version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile.frontend
    ports:
      - '80:80'
    restart: always
    networks:
      - internal

networks:
  internal: