version: '3.8'

services:
  backend:
    image: 'text_detector:iwx3t5uuhgwyw5vl'
    ports:
      - '8000:3000'

  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile.frontend
    expose:
      - '3000'
    depends_on:
      - backend
    networks:
      - internal
      - default

  nginx:
    image: nginx:alpine
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:8080'
    depends_on:
      - frontend
    networks:
      - internal
      - default

networks:
  internal:
